# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: traggo-credentials
    namespace: traggo
stringData:
    TRAGGO_DEFAULT_USER_NAME: ENC[AES256_GCM,data:mwJt6qQ=,iv:8wy9+nDfQLb4NFJKcXnLwShtChGsloz/+b1kfbZfBCU=,tag:AebvwbxaIsPwKSqgLjZ5dA==,type:str]
    TRAGGO_DEFAULT_USER_PASS: ENC[AES256_GCM,data:T1QNW1JFhApCRp/HKw==,iv:F7eGIuXIY+BlGlSbrTharFODjz1MI/w2x4YVkIJwHg4=,tag:GN1q1eokGKNMFvQWbHDqpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNHAvZ0xCcGRFQ2FNdW8w
            RU53M2pZOVRYRmpuWnh2UFNPb0E1SUtjR213Cno2dGFsZjloM0FLU3dDV0labGRU
            K20zblVlSFh2S1crOGxZVThBbnUwcjAKLS0tIFEzbkVFY1B4NUt5MlFhTEU0WlFt
            RVMrNnY3VDNXck5GOGhiVWV1b1JuK1kKYDjpRGRw3eppzrkr/gpI9vOVyRWfan0+
            QjN1wcnResK7fJ2U4GCwxmAE5XjE4DUtVWAiXRkXrewiHZLJWs82QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T22:17:25Z"
    mac: ENC[AES256_GCM,data:+aZQxoEVUDpQVsXRlsv58Ogm5+FFNiontrvXuWy57ocl70Wnrl9EMhkqqFjJRi1XXutBRGHgjwoD/fxnNdwotush/wV3DT2DBoy6gavmHo5d+RUSDpsybcQL0fzWRlQSA5UxtKYRFO+FlWfHWvYQxI0bx9uDhRpCX4HluD2odA0=,iv:+CHS08GrCc5xosSkQwjaE/BjrIeAK7ESwRbCnIAoHX0=,tag:R9xctq9GfPBC/ooqrMN9tQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
