apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:xDxRkH2TqiCWrrOFo42sQV6Xf/N8IKyLLABDqYd1heckhOOLA8/BQCsCquRKhbO8Vu2z5UptG0i7LepVQmPftSNCUAC0+BbbIy0m/qaBVBFhil7woqy+8hzVQN8w3BP+D6tWp2xN2AgxAziyUzSVUTjcyO3Rafv+Q4QypNMaSOE8Xu0Dh5gZeXo7sfejZ7gr9wdinaTPzEdRUp8kVfHye8LCwgfRlK0Auoz4p6uA1LKEJ3x57ruQi6L/aT+19KMytXihOsD3Lx4MrKn8WRtpZiUl5nJhaw/B,iv:dR34EsNpZAQXU8pGhYhGup43e0m3pwEuwqEo9JUQTGM=,tag:gANfNw7g9EbTkH88Gzlj8g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ejZ2SmJwMms3bkdFM29N
            VzVid2IyVlh1Y0dEdEoyQ0ZZZHIyWk9wWXpNCmtpWldybSs3c3IrenF3a0pUZksy
            T2xhV3l3bklXZk5hRGt6SThMY01pQmcKLS0tIFdYUXNKWWFSMmVjVkM1aCswNFgy
            aE1RaUNCT015bjdOVkwvVFF6Ky93cUEKqbEWUZpntNW8Wt6pMFgJty39RfnQgkeL
            Nf0RousIgABMgnZZMFV7ldGqkAdOjXQcgL0hjB5hV8fzlXM3W+H32Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T00:35:10Z"
    mac: ENC[AES256_GCM,data:FBrMT6fNp+lxvbBpjMpFbRI+XNvSGxuu9pYIyz3YmTmFJFOlXEHECGvLIGtboI7KD/ZCOhf+qv/00fNobikvE5uwUElQZ/2w5ckCE7SrtblAb9N6uasfRiPy7LIPUsBZlHx1Hs03Jze7fD1Nj5IU9Pv1Hh4UN6VQ2x5b0nxH4k4=,iv:sJbcUOqEsZv0q+tyNL6HMGrXHC8LCPzduXb8heD2/HY=,tag:4pEliZMAX340UHOkBWpDSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
