apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: n8n
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - secretRef:
                name: n8n-db-credentials
            - configMapRef:
                name: n8n-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath:  /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h 
                - localhost
                - -U
                - $(POSTGRES_USER)
                - -d
                - $(POSTGRES_DB)
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name:  postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
        - name: init-script
          configMap:
            name: n8n-config
            items:
              - key: init-data.sh
                path: init-data.sh
                mode: 0755

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
