# Template — fill in real values then encrypt before committing:
#   sops --encrypt --in-place secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: agendav-secrets
    namespace: agendav
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:gNC+lpaXx0+EJ/75dIi4dF0mtTDme1E=,iv:TyoOAKIKU7tuZmRm2wNN5sRLDWrq1YVCU5U7njWFgN4=,tag:yBAV16vw+hGO9g1qbMzjhA==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:feynv9z6PsPlgCIwmibbZyqDvMkX,iv:jL81VVNGOpMU4ZHrESVaEWTWcQ9d3rJ1w+iipCeJmFE=,tag:JeYsMwttOBGYNUlTB0Rq6w==,type:str]
    AGENDAV_CSRF_SECRET: ENC[AES256_GCM,data:fctuXxc4NKLvrG3R36CvK7m50BK8Bg==,iv:OtrlWgbb4JBbJdJ8Gdd0GCR9DqDmG/63If/fRaVQyzU=,tag:c24hpNEv7pLjVO6u3B4r4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaclM5OVpFM3JwZG5ud0ww
            dWJRQXRRQXZNVGVoV0dQaDNNVFl0ZnN5dUNnCkREWDNmYjZHdTZVUHhNc3lGMnd1
            Zm5MU21EajVDN3ZEOGVaRmZoejZzemcKLS0tIDIwZkFDMHNPb3BkcmFONzlWZXNo
            NFZtNjlOZ3g0R0RUazhUb09sRXdhb3MK8BWsqFwJUKgm3kIp2kF2Srlz/Vh8iCQB
            nlYoD35F1hNWtBNhTyFNToowlt9x5ULma1T1VvRUwvLEk3CrvX4FcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T00:11:03Z"
    mac: ENC[AES256_GCM,data:9bWvl+C4V0ec0363WIBIsdzNnZEgAJ+0mlJ/ytKu3qpptvg2i8RqjjbUi/5GLsCaagUkeZSXl9qrtnZkhpK7fJ1lzdLV8NaKq0lQW3IXvPvN1H/O4IPqfFZggO5czHveAClpmlK/K17EmR1eMMTFf9clG/fWT2ZNO+24FaC63To=,iv:VOVWhPlaFx3+ntY7/QqiGCH88/6Tf3RBEv1aDcVEDZw=,tag:ldm0G601t2xuqdVUyMFuVQ==,type:str]
    version: 3.13.1
