apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:xqfH3XtaSobhORyaHyTavG3+TE33gPkE/isKbwaXj4SduSCbjURfHfdC2L8mkpWw8I41rCT56tqkpx1QCxLmd/VIxlLaRUy+Fv/mSGjRzrn0noPs+0C0S1yHYwptfubb+IHDCmXrST15ydbFTdrVIm205745SAjrKXoTzBewKnuce7CkbDifU3aDyI+Y82qxu5+iXFFVvBnNYSEj9C/UVfG941ulJgd8+oHe7sg4P/WnUF7223vBRoPgR99W6Q/5u1lGA/iVqv5KSKoAHEwh1GwhshKNmDkIobQ+K/9UZll0wPxF9DxewnFhIEs=,iv:1MJvD84sUqA7WOoTbz8+nHAOk/qtsFFbMgpXm7b9Znw=,tag:KukP3gHhGKlXesYV6iVZFg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMGt3TUltS082SjhKRnB6
            WUE2ZzNlUDFRaFhGSDVJTWk3ZldDcmxaRjNnCnF6cnJLRnQ5dUJuZkpRR280bkJk
            dnBGRTBlWURKQzNvdTNMTVp0SEpJTE0KLS0tIGZvY1hmSDVNd2NQL3hZZkhzeTBM
            UjA5cHJMTTZPekZTSlJwdVhiU1pEZFEK82s/K6k+f51ERMIaKAicyvj4UBIWz5+6
            pwvm0malgDcWw3wPaN8MXiNZ1jJWx/wGGAJ81EYmtFzIeOL8QS75qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T23:50:41Z"
    mac: ENC[AES256_GCM,data:8vRVAMZwcNjI8nWZV50DRMszl1p4IlX+zvSL7W1KsLHVOCeQZThg0LUdaXSo1eXNsmnt+x33GGKvsNNyKgceUE+F4w3eMDXgzUogzWmdYlqoykGsJSRNG/aNyhtgORTRwPqbktuYP6ZNS7qrSyaU1vJNRqFHRvJJDZzxmGQgS5w=,iv:wo0KrvFSQtopyX4dxNcBN05j2IqLpCP0V2vU/62S9k4=,tag:FoFaX8dxokyMBkgvLFzs7A==,type:str]
    version: 3.13.1
