services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
     - 8080:8080/tcp
    environment:
     - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - /var/opt/data/ollama/webui:/app/backend/data
    depends_on:
     - ollama

  ollama:
    image: docker.io/ollama/ollama
    ports:
     - 11434:11434/tcp
    volumes:
      - /var/opt/data/ollama/ollama:/root/.ollama
    environment:
      - OLLAMA_LLM_LIBRARY=/usr/lib/ollama/libllm_cuda.so
    gpus: all
