apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rZxn9Qd0chmZ9fI/foaPnJlxNDPXVXL7KsWqKmk71S2lMmOwS3UxWWAl2IjHNayXh014TFpqezIZr2L2XArVimmY8ozEyvBssXXG9OEBjhapcVrpkBPh8+iMhV4VTNoFUZRnmwbCgGEpHqEWayOo+NNFZbdW4svfqbm18y27spmsfXc0LYsaJklnhnjoHpBTSK6oM+aSmVbN+XHsFq9C2LbUuN4AWaWvqQiHujtikwMPKDa8PATRBO4dYoP1DUGBDZj6l3J/7LCegTmVA2Q+Em1Z6PklYJ4mjTifSc70GFAKp8tBdP0GohlnKU0=,iv:LG2Lpdv9XlyHMPbcJzSSsx4vZsbm0w+r4qX/aVWh6ZU=,tag:gnkxA0HETIgft3Z0kqvoBA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M0dMSHN2bmh2UUdrbHhK
            eFZKbG1nY0JaSTdubEpFS3BUaTNIUHQxSFIwCkEvdnROZUpUT2N3TmJqaHo2T3lS
            QzlyUDFUSTcwUC92WmFGR3BYWTRocUEKLS0tIGZtRnRtSjBmL2dUcGRKSVhLcFN1
            YTVNMGREalZxajBqdVZwTStNbDNXTDAKMgmnvjqtCkB23HX9NV0F+34yyaDMWHVW
            ZHdsn0y6oVcx9bgvIOvOrxBRocv8DAp24AsyOYe5fqmvoSIeNEA8dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T08:30:30Z"
    mac: ENC[AES256_GCM,data:gzkitIeP3lX3Yr7EptSk0zzt8oeZzB95am/7AZNpCJIr9JVXwogIaej69KJ1AYxEJmIP/kehsSUQcYF4A1nf/0tZKsL6n91/zMFA0kR5HB1YMdvXxZPiZTYfz88fJf/xwhl79qCpgEs0SsMUCENn0pJGV2GBABfIgpWFc3yvfek=,iv:jR0uhqejBMcfdJd+PQrKY9x/0IJAUtvuSdz1u60w29k=,tag:/tJBxxN/5wUV0edxeeegKA==,type:str]
    version: 3.13.3
