apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 5432; do echo "Waiting for database..."; sleep 2; done;']
      containers:
      - name: memos
        image: neosmemo/memos:stable
        ports:
        - containerPort: 5230
        env:
        - name: MEMOS_MODE
          value: "prod"
        - name: MEMOS_ADDR
          value: "0.0.0.0"
        - name: MEMOS_PORT
          value: "5230"
        - name: MEMOS_DATA
          value: "/var/opt/memos"
        - name: MEMOS_DRIVER
          value: "postgres"
        - name: MEMOS_DSN
          value: "user=memos password=secret dbname=memosdb host=db sslmode=disable"
      - name: db
        image: postgres:16.1
        env:
        - name: POSTGRES_USER
          value: "memos"
        - name: POSTGRES_PASSWORD
          value: "secret"
        - name: POSTGRES_DB
          value: "memosdb"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: db-storage
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
