apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
      - name: memos
        image: neosmemo/memos:stable
        ports:
        - containerPort: 5230
        env:
        - name: MEMOS_MODE
          value: "prod"
        - name: MEMOS_ADDR
          value: "0.0.0.0"
        - name: MEMOS_PORT
          value: "5230"
        - name: MEMOS_DATA
          value: "/var/opt/memos"
      volumeMounts:
      - mountPath: /var/opt/memos
        name: memos-storage
      volumes:
      - name: memos-storage
        persistentVolumeClaim:
          claimName: memos-pvc
