apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
spec:
  type: NodePort
  ports:
  - port: 5230
    targetPort: 5230
  selector:
    app: memos
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: memos
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: memos
