apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silverbullet
  namespace: silverbullet
spec:
  interval: 30m
  chart:
    spec:
      chart: silverbullet
      version: "0.4.2"
      sourceRef:
        kind: HelmRepository
        name: silverbullet-helm
        namespace: silverbullet
      interval: 12h
  values:
    image:
      repository: ghcr.io/silverbulletmd/silverbullet
      pullPolicy: IfNotPresent
      tag: "latest"
    
    # Admin credentials (dummy values - will be overridden by external secret)
    admin:
      username: "dummy"
      password: "dummy"
    
    runMode:
      readOnly: false
      syncOnly: false
    
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    
    service:
      type: ClusterIP
      port: 3000
    
    ingress:
      enabled: false
    
    volumes:
      - name: silverbullet-space
        persistentVolumeClaim:
          claimName: silverbullet-space-pvc
    
    volumeMounts:
      - name: silverbullet-space
        mountPath: /space
  
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: silverbullet
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/env
                value:
                  - name: SB_USER
                    valueFrom:
                      secretKeyRef:
                        name: silverbullet-credentials
                        key: SB_USER
