apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "2.0.1"
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    enableRbac: true
    serviceAccount:
      create: true
    
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: "homepage.fcosanabria.com"
            paths:
              - path: /
                pathType: Prefix
    
    config:
      kubernetes:
        mode: cluster
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
        - Learning:
            - Skool:
                - abbr: SK
                  href: https://www.skool.com
            - O'Reilly:
                - abbr: OR
                  href: https://learning.oreilly.com
            - Udemy:
                - abbr: UD
                  href: https://www.udemy.com
            - Roadmap.sh:
                - abbr: RM
                  href: https://roadmap.sh
        - News:
            - daily.dev:
                - abbr: DD
                  href: https://daily.dev/
            - Hacker News:
                - abbr: HN
                  href: https://news.ycombinator.com/
        - Entertaiment:
            - Last.fm:
                - abbr: LF
                  href: https://www.last.fm/
      background:
        image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
        blur: sm
        saturate: 50
        brightness: 50
        opacity: 50
      quicklaunch:
        provider: custom
        url: https://www.kagi.org/search?q=
        target: _blank
      services:
        - Infrastructure:
            - ASUSTOR NAS:
                href: https://asustor.fcosanabria.com
                description: Network Attached Storage
            - Portainer:
                href: https://portainer.fcosanabria.com
                description: Container Management
            - Grafana:
                href: http://grafana.fcosanabria.com
                description: Metrics & Monitoring
            - Homepage:
                href: http://homepage.fcosanabria.com
                description: Dashboard
        - Network:
            - Xiomi Router:
                href: http://192.168.31.1
                description: AX9000 Main Router
            - ISP Router:
                href: http://192.168.1.1
                description: Claro HG8245W5-6T
            - Pi-hole:
                href: http://192.168.31.68/admin/
                description: Network-wide Ad Blocking
            - Nginx Proxy Manager:
                href: http://192.168.31.68:81/
                description: Reverse Proxy Management
        - Services:
            - Syncthing:
                href: https://sync.fcosanabria.com
                description: File Synchronization
            - Deluge:
                href: https://deluge.fcosanabria.com
                description: Torrent Client
            - IT Tools:
                href: https://tools.fcosanabria.com
                description: Useful Developer Tools
            - Paperless-NGX:
                href: https://pln.fcosanabria.com
                description: Document Management System
        - Apps:
            - Beaver Habits:
                href: https://habits.fcosanabria.com
                description: Habit Tracking
            - Linkding:
                href: https://ldstage.fcosanabria.com/bookmarks
                description: Bookmark Management
      widgets:
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "Cluster"
            # nodes: - Since I only have one node, I don't want to show it
            #   show: true
            #   cpu: true
            #   memory: true
            #   showLabel: true
        - search:
            provider: duckduckgo
            target: _blank