apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "2.0.1"
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    enableRbac: true
    serviceAccount:
      create: true
    
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: "homepage.fcosanabria.com"
            paths:
              - path: /
                pathType: Prefix
    
    config:
      kubernetes:
        mode: cluster
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
        - Learning:
            - Skool:
                - abbr: SK
                  href: https://www.skool.com
            - O'Reilly:
                - abbr: OR
                  href: https://learning.oreilly.com
            - Udemy:
                - abbr: UD
                  href: https://www.udemy.com
            - Roadmap.sh:
                - abbr: RM
                  href: https://roadmap.sh
        - News:
            - daily.dev:
                - abbr: DD
                  href: https://daily.dev/
            - Devopscube:
                - abbr: DC
                  href: https://devopscube.com/
            - Hacker News:
                - abbr: HN
                  href: https://news.ycombinator.com/
        - Entertaiment:
            - Last.fm:
                - abbr: LF
                  href: https://www.last.fm/
            - Hardcover:
                - abbr: HC
                  href: https://hardcover.app/home
      services: # services.yaml
        - Infrastructure:
            - ASUSTOR NAS:
                href: https://asustor.fcosanabria.com
                description: Network Attached Storage
            - Portainer:
                href: https://portainer.fcosanabria.com
                description: Container Management
            - Grafana:
                href: http://grafana.fcosanabria.com
                description: Metrics & Monitoring
            - Homepage:
                href: http://homepage.fcosanabria.com
                description: Dashboard
        - Network:
            - Xiomi Router:
                href: http://192.168.31.1
                description: AX9000 Main Router
            - ISP Router:
                href: http://192.168.1.1
                description: Claro HG8245W5-6T
            - Pi-hole:
                href: http://192.168.31.68/admin/
                description: Network-wide Ad Blocking
            - Nginx Proxy Manager:
                href: http://192.168.31.68:81/
                description: Reverse Proxy Management
        - Tools:
            - Syncthing:
                href: https://sync.fcosanabria.com
                description: File Synchronization
            - Deluge:
                href: https://deluge.fcosanabria.com
                description: Torrent Client
            - LazyLibrarian:
                href: https://lazylibrarian.fcosanabria.com/authors
                description: eBook Library Management
            - IT Tools:
                href: https://tools.fcosanabria.com
                description: Useful Developer Tools
#            - Paperless-NGX:
#                href: https://pln.fcosanabria.com
#                description: Document Management System
        - Apps:
            - Beaver Habits:
                href: https://habits.fcosanabria.com
                description: Habit Tracking
            - Linkding:
                href: https://ldstage.fcosanabria.com/bookmarks
                description: Bookmark Management
            - WHOOP:
                href: https://app.whoop.com/
                description: Fitness Tracker
        - Media:
            - Photo Gallery 3:
                href: https://192.168.31.7:8004/apps/photogallery/#/timeline
                description: ASUSTOR Photo Management
            - SoundsGood:
                href: https://192.168.31.7:8004/apps/soundsgood/
                description: ASUSTOR Music Player
      widgets: # widgets.yaml
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "Cluster"
            nodes: # - Since I only have one node, I don't want to show it
              show: true
              cpu: true
              memory: true
              showLabel: true
        - search:
            provider: duckduckgo
            target: _blank
