services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Nginx Proxy Manager debe escuchar en los puertos HTTP y HTTPS estándar del host
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port (este ya lo tenías en el host)

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports (estos son necesarios y no compiten con Nginx Proxy Manager)
      - "53:53/tcp"
      - "53:53/udp"
      # Elimina o comenta los puertos HTTP y HTTPS para Pi-hole en el host
      # Nginx Proxy Manager se encargará de proxy la interfaz web de Pi-hole
      #- "80:80/tcp"
      #- "443:443/tcp"
      # Descomenta el de abajo si usas Pi-hole como servidor DHCP
      #- "67:67/udp"
      # Descomenta la línea de abajo si usas Pi-hole como servidor NTP
      #- "123:123/udp"
    environment:
      TZ: 'America/Costa_Rica'
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

