apiVersion: v1
kind: Secret
metadata:
  name: solidtime-credentials
  namespace: solidtime
type: Opaque
stringData:
  APP_KEY: "base64:yCBBfL+ULWuYlgqAixBIiPJhS9GbLp/pjUuKCrQ72h4="
  PASSPORT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDcv7fTDm1M1uqA
    gDtiOrGEBmTR2loaT1dJSohNC2/zaEwQ2QQ0yBrQe4SUSMjXWVaSeJW79kUSzGCS
    HDZqQmr5wm7t+zAe8LuDywUNXBCfwizlo8BFJabMzInB5XlO/GckXGKIkgs9OkFu
    LuRu45ArpJpX89dBKoTOsT+aY/ae/inojtdko0Cso+rxTCdLr9gerX1RwW5p4FUY
    lB+Ihl0APBXWBet1uQ0LaoWeSpIyCVYKB2Sv56TKCl08oWizLrfNFNe1u4T9uH+O
    Q6Ih2Zv7/enQyfBKq77dP+hSiZ2SQoxSDdlf180R9zWiV1kp+5riBv4ZvF9AIdWv
    355jDNvDYLlNfLQi3dW8uonfPGJOZLq+3S0RJVHiNhMu4k2S3qd6kEO3D1UYsjYm
    a0b4nsOuqqhUYAyt6an2mlyaOxbxd0gH/9OggQSi54RhmZO+UQjk9NuGaYYchYkA
    7h3mSmfuOyWntH5ImKyUWJoalia5vL2Y5fH2FtGqDRzJNVMw2hEOff6FxTRRQQwT
    FKKEGuVoZpcOpEklRpC+QxmsFZsn4CyPRDGCIDBq49vAd9Ykb8iSXOkyPYfpICC+
    pez0/Yhre1tMYKcF246vtgMPuSLqgn9Doa04gSGC1e19Y7Kzm3Qm9sLbtikMLZsQ
    mivsqlql7PftpOoNN4X6olMLgMEFcwIDAQABAoICAC6KOP5FR2Pw16XZ4ys1hqF4
    G59msqJjYdqw3QWpSKP/tDHFHy7llUmpEO2WXsmQK0FcLO1g4XUyI5YKXqqOcDFR
    /cMstxt+03nYvqrvYw3biU2s9Wdepcj9wnlfoPC3JCO1WozChZ4V/x90wXJjhcy9
    ulCatyIlDbTqB6fMNX2Vxk4id2TfSk5bjLfsv0gkvaLSHt6ysk2eHzK8X92PvmHD
    STNDMj4ykn56qcsSm7ny3/HjVyYC52o1Pyz+Nq24RsX1A/lrnIFFeZcLyU3rrAg3
    oykCuid0CBxrUda87rycTSsrgk3DmJeWD/e3BLRmOGQ45y+T2F0UBRI8Sg9F8bre
    E8slrEcbTVOifhaHnev94iWX+RhoACj20C8ijXwy0uYWAucXr4MX4uES3Egk1BGD
    OBU5Xzlq8PYIoGfYUhJjFExND29uaNDfs9ocaMQ0BrIFO+U/kQ8LBIwjYFWvmdDH
    FVuIbfGb85KdkyaX5QCntowHGSh1NH/+hAl7eBdBXqcOs+5iuqPPKPefnhiLuhLu
    8NrJQE4RptAbDoGITZXsm7z63fiKYYiUX6DJBlQYlwCIAK+vLGLUqDuOR12eqnxy
    Rgh/KtbY48jXoITmr2ePAfG0sE37JtdldtOqYuTs+9UIOptgyU3Q7yVU7Pfjq16i
    iUT0xzlEQYLfLJRLxGIpAoIBAQDx2wC7Ei42Znfgg9+LI1yqGyA3gpv6Gdzx+9KI
    S5BqCmCpHO3QslCf1VNyI6L825U3Vh2CF9V58W5lVrmFzZTlEYOVWfYVax22KG3d
    um08roGUtm162MJ4jidxKWe6Kt6v7OzsuQNyZBaviXMmvSnN9hn0jE74CGoxHzYe
    6SWc4Yeeh2/mLkA9yPb8QfqDeT5OeYuKycOVqrwxOZaexD39B5q1TbbkrWXh7JZE
    ndcL+nZMBmmOWhGMCW7HE0dE5+PTBz5+yAG+Jst/Ozus+p3smusMq8vPM1nZsRHo
    G0gZwHB3/fxTDkoVyzeiGvVhofU1XqI3dAdBohX4mfojG+zNAoIBAQDpqLaGBUAz
    ODlGarKQ8YE/7d9rH5pCiPN6zShPxNqFrRLracM2Uvxn3dBnE3S9HsTYxNaWbjBG
    LJwdHSPbu8bc555PsFUaKjyJCc2GP/yrlGXvCJxvT4ig4I46rAfWfK2zKk2xKGAJ
    FG973H6xBvJSNvupLACQ9LGVUxSzCdomaqQ26sWiFb/mu7r6yxHi0dCV7HSNoPd9
    aWAZ8TFVbne2+ueT0bP98TSpvNJUJFO1mp5MaXgSboXeoKyE4VndA484q5pR8LEA
    9CvREwE2+EB17ApYdMkREwn7gmD5OAOV/pozs177QvPaw1+SqFLkiUpQslXSI2gT
    TFBolshSiLs/AoIBAEVLQw1WKylo+GW6Qt0hl5YhSXy+DiR9LoGibfKg+9J2ALXT
    VQvbWyBARbVJIpSh8UG2iaPRYlea5c9hJqyAd22eM/4hlVETrKKZOMkzdcLSGMxb
    7EgrPKS/zestOsvrJnxvPH6ij6tBpAJNNlHeFtEs9sjLPoDwIETMtXvrvtwQ/gNc
    uKHRlJRfNOyXlsf+f+yKBIISRthl35+W6WG5xizt9dSGXKVuTOeLGo60Tn3fF++2
    Up33jll6BmRBUMUcT3kR9UTr1xv9D4b3mKR59a9pv3iU7EMEanTlt8SxtFm0ekTW
    32mIiY9u9xSZ9r4vYgsVfxK2SrHyV6svqqxOfu0CggEARsDczEZow1nCFi2W9sb6
    kWYxYhnGt2ELAWOAUm9UkGfxM7Hp99g3MCh9w8ijb+USTGWGaTTij01Q1IwPYKlC
    tX+5c338txiVDhYW0xErLLWaDEC6RgZ6Y+S7jM6s7OkCHB+yOPP16Kn0fDgvcOGe
    nQCjQf3eCgbeg04OFYzlLv7ZzPtYbxVQ78hm/SxitSE9nThlrsFQT/yJqjFb8/eo
    bpMZbqxwaXQRs1hHBE2fv30bdB33yvUGunxC4VXvxTofs1RbPXa50oUdg4jStFeG
    BW89Tr3GaNIwEqXPQYgRpejbvs4Q89q5RsQke59WwndENp1Z2XD5Qea47oLCFCPt
    NwKCAQEAgqieTPXzlKXjocREpA2MqWfohdjkcgbZqhVeRRbq5Ha+uy96Awlr3pwi
    uig34Gaaw1xo72aUHPf5e/dygYOzgWTSR9cg/FSRwT8LZvsGxnNh+c7fvbnVYflg
    gDr0lzsnp72z0G1Q73SfpHDN2S92xseAAz1lKFKYJ7NQ13bvOi9wvqD9LjzbydIa
    s3AV0YNhj/s2nQxyva21h3R/qVM833NfQE83l2jSBiV61VCGLEs0qNQ4jAQk9okQ
    lOCvryOi9L5n2TzJlSsK9WqAmtWCo2uro5KwwI/LdT7DDy5wRe7f5a24/mwr/uiJ
    C1sOPEANeKMbxWUf9sMK52XRj6xjZw==
    -----END PRIVATE KEY-----
  PASSPORT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3L+30w5tTNbqgIA7Yjqx
    hAZk0dpaGk9XSUqITQtv82hMENkENMga0HuElEjI11lWkniVu/ZFEsxgkhw2akJq
    +cJu7fswHvC7g8sFDVwQn8Is5aPARSWmzMyJweV5TvxnJFxiiJILPTpBbi7kbuOQ
    K6SaV/PXQSqEzrE/mmP2nv4p6I7XZKNArKPq8UwnS6/YHq19UcFuaeBVGJQfiIZd
    ADwV1gXrdbkNC2qFnkqSMglWCgdkr+ekygpdPKFosy63zRTXtbuE/bh/jkOiIdmb
    +/3p0MnwSqu+3T/oUomdkkKMUg3ZX9fNEfc1oldZKfua4gb+GbxfQCHVr9+eYwzb
    w2C5TXy0It3VvLqJ3zxiTmS6vt0tESVR4jYTLuJNkt6nepBDtw9VGLI2JmtG+J7D
    rqqoVGAMremp9ppcmjsW8XdIB//ToIEEoueEYZmTvlEI5PTbhmmGHIWJAO4d5kpn
    7jslp7R+SJislFiaGpYmuby9mOXx9hbRqg0cyTVTMNoRDn3+hcU0UUEMExSihBrl
    aGaXDqRJJUaQvkMZrBWbJ+Asj0QxgiAwauPbwHfWJG/IklzpMj2H6SAgvqXs9P2I
    a3tbTGCnBduOr7YDD7ki6oJ/Q6GtOIEhgtXtfWOys5t0JvbC27YpDC2bEJor7Kpa
    pez37aTqDTeF+qJTC4DBBXMCAwEAAQ==
    -----END PUBLIC KEY-----
  DB_PASSWORD: "solidtime-password-change-me"
  POSTGRES_PASSWORD: "solidtime-password-change-me"
