apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Npn3e8YO3ieSLcM3VNDA6nbF7jlwKTC+SUgHgxlk5N2RcP1uD0LN68yNq6AcTGs/Cx5zWqd/HeJqZYkVaYOlaPq9EBvl/WpZQKe+NbcIROD+pEEEbYDinV/mSTZsLtxr8hJnP4fJfIl39p/lmFfOJTigBy3CfXRiG3T0XPw2sevw72MOE+bW9289U0cjnDBlS8FIUs2zWxBC1D5Hc5qwy2gz7Y6UDZy2OFd4y+7jrWmwTETt31QAjy36Dy8FWQ0Ok7MMUgQxV4v1/Crpo1EY816YXedVJKFa4Iqxte1llgnSRmckRJdyv/JZL+Q=,iv:WzR8DvngGsNZRR5N3y/TGn49v9gCiskjyEPedsSpW6E=,tag:oH6Vs5np33AfNlAqSHaayw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRnR1TDVaOW5ZSFA1TlE1
            Ti9ucUZrb1hhWitEdWdWTTlJa2c5ektJUXlJCjA0VmxSd2FLMGp3SmVTb2NqSkV0
            djBaOWcvQjZqOWRIUlk2cTdoa3ovN00KLS0tIHlXOXJINXhjYW5XOW5HMVJoMjJa
            WCtZY3lWaDdKb2llYVNxcWEyYUViUmsK5IXDT4UTmW+5exAjXhcVb1MrCad7Ix/U
            uJ3xW/HPstxDeK+tKwWWvSB0nguxOyO8Sbet3sxU+JuElTC2t8qDgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T23:03:32Z"
    mac: ENC[AES256_GCM,data:se0pL1IxusztKakBXcYkv4V/RzirJfSguptI8HF9tHNv0s8bjn4b0tFJJaBtnedOvaqHabHacVRQa6WJI43zddMyAyB8KhW5Pv52AqhadttofUQC2BIlNRyH6REguaSbDtC0Qm5rg22ZYg4yjjEYsL13PeF9aODX17nqCdW482M=,iv:0Zo6mnMt/mWmH9dQ/YwuXhEpsn+rSnxaTPvP4EJX0vo=,tag:fWZkAtJXi+KAPS0oU97aPQ==,type:str]
    version: 3.13.3
