apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agendav
  - baikal
  - beaverhabits
  - homepage
  - linkding
  - memos
  - traggo
  - trilium-notes
  - wallabag
  - wger
