apiVersion: v1
kind: Secret
metadata:
    name: wallabag-db-secrets
    namespace: wallabag
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:xE35hBuxlCVB,iv:bY8FgCW7Os2PqnDoOmxHQLaHPP8oZc20Q7dN5zjugSg=,tag:tJgzDgS26vNDE/VEis4fJg==,type:str]
    SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:NZ3fUQRte9u0,iv:YyjgKtNqwuOpg3IHWwjpJpCIlc+FTLIColLRleVQiQs=,tag:bzzgNMZKJKbw7LqiZgbJWQ==,type:str]
sops:
    age:
        - recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWTZqZE5tV1RCRjd1TE9J
            TVFQNGVOdmJObVlzeS9TSlBYY2pheWZ6UDNzCmluWGN4d1oxZ0p0UjJjTjNJazFW
            bnhtTXFVNWFHejdQTnVnNGVnQ3NHUU0KLS0tIDlDM2RqZ25NYVFUWUhOSVEyREFP
            WkI2UFlzMzNiMnFCVmRoNWt6SVVRcncK+17R8eTOt7SmLz4We8x7lnaxLohXEXp/
            a5R4oiJMlKwhUa2vuf5bk5Xq2u82GZD+BzpaetAghXFM2DqBD/iQtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T02:49:35Z"
    mac: ENC[AES256_GCM,data:lDeXmRdC37r4EipanTqYAsaDkh9jTv/CYHDwX3QOyKmKViz7FF8cWoQuG9bVXxL0Ce1dOJPV8kWfu59+gxybrTGFBUQHq1zFpy5HVLbMj2DRScPYaOGGMhSey9hg3vJMLbJekgihCuXaL1kJH/Ws4x5Rskl+ORQguMQCeMh3lyg=,iv:/juAOUPkC2McIr6wIQ8Y2kjneB1YTmY8Sz+Xh/kTPvk=,tag:q4dHMplCyxbmrllAEr7WqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
