apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:3w03JljAXbKvo7wKOiN25K7Lq1SytNLqWB4aU5n8PszVS8ugBIiMoIjoB2KWXxmj2rZYHcgkO/P6kV5Uf+hcIwhd2laPFuPwY12uqISZjCyNM0Ep5ITJEGY9iDuwl1ZL9W8XBenYevH9ngO/2YNG81Gx8wI6pwbqcI6n38ZT5CZ8nK/GNtgF8ImV1RsCmQVmQCYakiEeOL/2N3DuZPS+kyLmKBtA5bPVeDN8Zzabip1L9m1RrUhvwzbsBZ4qgtk2VXEC4w3D+PBchp+IHnIligThZbf6fAvhOuVFmVn8OGzvOfUiboNDeoW0gHc=,iv:JekuToZSxmRQmDEZXlyt0ruxIfUkDlXljuT1PSn1BaI=,tag:8gqGLOpwT/Zd+f+tbjyfTg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b0VBNjE2bVdGb0N2bUZw
            ZWxZMUovYjlUZitkTkxUZDNQSlRDVlpQYndNCmU5d0pFeWU1OUlnbVNlQml6ZGEy
            VlR4R0RzbnRzOTVraFlQbkdWY1NGZW8KLS0tIDdBLzgzdmc4bEZxT05VTk1SMEhB
            c3JaaHJCWjdmTlo4Q0owYW55dXMwVG8K09DIjSp6uoJVZRY0WybPap164shMTkti
            anVjC1uF/AQ4190EsMu7nxXyr3M/mEFeOuveNpbs2bafptco06rVNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T02:21:53Z"
    mac: ENC[AES256_GCM,data:uLNh6kD83X8iWCaeeeF96GnUvMPdNC37zfaRaqZdEGhDj4dB2K2Wh2yTC9FP19y2w+Kn6v9H69+1DCzeHhal6zSdQM09LT9zzcvQDr/7zKthBKdPii6wgjoToQzqPUEVxDwms0QnxQ3D4ZS3S/vWo4WOZXmqAFpVHWoI9jWdRXk=,iv:t1WKu3NfsMdZoz2GKxZlTPWjv+1W8xKcE4ptiRO/GmQ=,tag:jsCq9yZQ/hX1H5NfCCI4ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
