apiVersion: apps/v1
kind: Deployment
metadata:
  name: traggo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traggo
  template:
    metadata:
      labels:
        app: traggo
    spec:
      containers:
        - name: traggo
          image: traggo/server:latest
          ports:
            - containerPort: 3030
          env:
          - name: TRAGGO_PORT
            value: "3030"
          - name: TRAGGO_LOG_LEVEL
            value: "info"
          - name: TRAGGO_DATABASE_DIALECT
            value: "sqlite3"
          - name: TRAGGO_DATABASE_CONNECTION
            value: "/opt/traggo/data/traggo.db"
          envFrom:
            - secretRef:
                name: traggo-credentials
          volumeMounts:
            - name: traggo-storage
              mountPath: /opt/traggo/data
      volumes:
        - name: traggo-storage
          persistentVolumeClaim:
            claimName: traggo-data-pvc
