apiVersion: v1
kind: Secret
metadata:
    name: wger-postgres-secrets
    namespace: wger
    labels:
        app: wger
stringData:
    POSTGRES_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Xaq11j5U1/DbxJmQnYYt032MdDIFjQIfgZDJ1tuNuyo=,iv:8ZYWtFLaNT4jt9pleDbAhLayExnqOpUBrFUwZNQB2kg=,tag:niD236CFP1hs/nKLudbreQ==,type:str]
    POSTGRES_USER_PASSWORD: ENC[AES256_GCM,data:l+WeTj5xdxvdbFAbaEH9KCf+SLLV/nh8zFO323J5mA4=,iv:fUtLTPzLpiqDM7egNZkpteCj1VdPrPy6olIzZE5rjMM=,tag:ZqUi57WlybUNYIo7tx0Dsg==,type:str]
sops:
    age:
        - recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld0xIN3Y2cDVyQ3NrT3NW
            d1lCOXVmMTNVV050emlXRURjc1N6dlJnSVJJCk5VMDd6aG1qMHBOOFRORzRweVVr
            R1ZZdnhTd0hGT1E1Nyt1Q3h3R2pncWMKLS0tIEN1L2VBN002d3hqRVh3bkJkaFpx
            Qm8yWFBQcFc3dG1VaFdwZTl2T0Q2RkkK3BJRFQEN5HBeTWimC1b5y+xWCro0JX9y
            yvJ8NwSBd9R6/F8AVnYZMvausfe2Cglmd6Mu31UtcQErv763aqv+Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T00:30:08Z"
    mac: ENC[AES256_GCM,data:ZBYS1pBlXrJraysEAXyw95DIqc/yezDmjOrIT14eiD1kJgKpFIj7THQK7KaUxNChWCMQHn/qX/K2GUtE5oRksOToAi3BwO7sXqS+XoO1YQKDSCzhwKfHMOxIWcGmjRF6718Hh4Id9sskaOnSD2IWOwudLEqgRIN7sYY+HeYwUd8=,iv:+8rhhSn0F+ptKYkD5/kpJcm2Vpze/RfZVBsmJERQRWc=,tag:9HdKKqM0NL7jOVAN6WeEKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
