apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-media
  namespace: wger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-static
  namespace: wger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-celery-beat
  namespace: wger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-db
  namespace: wger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-redis
  namespace: wger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
