apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:FfBmPuR8FsNlaxlU8gyYpzztxXrvaCkbNkiFys7DvFpFEq/HkliNNXyki5VeX+o6Onw1tVdwnzuhHVL1SKFLeqb0rCw9MjOToNTTfYuHpu3MXZYIrmX4pGPjK2G47O1o2reHCiQeUAywIL8TyYMRTvcBssBhQ9kqeqEKxnaPWsP4BheIwPZLEmSZlE3dXOzNcK+yWFNzFxC4t5ywgEulTfcZaoP9phvCzP0KOH/Ip4yJ9W+l60FGTKkVrCo5YkXogAJew4v6bjv1BU1ckp/je1hWyA70Yed8kEKjzqhMcHtmxfURHQ+kmUxF79k=,iv:OnQpP9fkj/8Lv+XZkyLrovvAOhP80dhfo9HD+0cMhkE=,tag:2HbgAJLXjHL64Jk31GoaRg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNVNmRUdUUmxTN1liRUFu
            UTBvenFPYXNlZjZzQ3FmK1U4ZTNqbGRid2dBCjZVc3FlMEY1L0VFN1pmUW9HdjB3
            NWlqMTFuL2diSkVJenZpdnl4SU0xa28KLS0tIFdKT2NQZ2krcm04MVROWlVJVzBp
            RWc0TjM1MmljOU1DZ1AyRDl1VWpzNm8KWmvMqmfqBVqywMOLoxrKdgEddMiQ7ORo
            0V0j8aQ22S9SiOyac50hW4t5IBpxLEq0DYjF3MzJ3R+EML7N+M18ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T21:09:37Z"
    mac: ENC[AES256_GCM,data:Y0lY5MsW+y6jwXZpoxw1j6PwNSFUtJqxPyRhjSF3QBIifBw5RowxwNLzfcG0HcEgjtj46GtB+RAYXWzFOCIgSuUgnlY3oqqZNQO3Lt9OjckYqjViYn5aBy1OpY+nq51TYEaJRusM81NS+JNjCtVmKwcS7qiilU7NqUtRj+uJWMo=,iv:85D9KMEC7QAxQ4hCj+RjnJUzvHkfriHs7S1kPsy39lI=,tag:u3XYYosLdjDVDIv501DcOg==,type:str]
    version: 3.13.1
