apiVersion: v1
kind: Secret
metadata:
    name: tududi-credentials
type: Opaque
stringData:
    TUDUDI_USER_EMAIL: ENC[AES256_GCM,data:AyH64pnBbkAy5Yy9A2Er,iv:0o+DlilJUqReklsE/KK53Stf+hFsBubN0fSjkNNZkic=,tag:5UbE5m5psJi7NUJyeTMcNw==,type:str]
    TUDUDI_USER_PASSWORD: ENC[AES256_GCM,data:V5+YfQP4plvtNK1juHZoI7bTKMc=,iv:8fjvXmG6qs7FZWJL/0S7k1S+3o88gp0gP6BZMqtOv2g=,tag:Fb1bBpsNeZZVlFfGkcj0Dg==,type:str]
    TUDUDI_SESSION_SECRET: ENC[AES256_GCM,data:8+1SXKxmMrB0BXoFYa7fFBC3y0l+/Chq9HmYrI0ygRpc3D9UKXGyKK97puqIJnhIPf3iWC1THtHwTdDYY0UZDYLDlGtNW9nCUAbEgF3QkfnHmeS3EPpSesJLgKl5RnHI41MCeInKhJuTkSvVsP2cwWst5pZe25jLvZq8KMU9ui0=,iv:PllLmXC5GLizqTF5kekIt2qewrrOBnYX0ySmD4bJnTM=,tag:8XsXx9FbjD6nnpb/xM8dmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c0hYbUpsLzlUdGhWdWZt
            NmNmRE91T21DTjNuNndnV0s4UXFiODhrUWhNClJXZjN6dTZlcmpzWE1OdVE1bmIv
            bktsT0Q5UlZ5UGdzWW0wbzRWb0Mwc1EKLS0tIGt3RUNmMlBSdndsRVhERkxiVlJz
            MG8ycEVYMmx3SGk2YjhhQ0lvUFpxcFEKE+Xv+Vp0zX66M5U6oulc5VzpKXYo1kNo
            uZ13tClUtDPtCI3q9q7UBvFQZQdOHU57l5YUSuHHwY+SWyOQ0eHehQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T19:15:34Z"
    mac: ENC[AES256_GCM,data:eJxUATIMlZDL36pOhhAbJf7JA4DmjF2rV/f0+ImoqfYq/amCNejF01V0GmufND1FU+JjP+lRd7p8FR+ucX3FYA6pbxKdpu8tRvJ6L4se/25WrD4ouWxdWdeBpDSm7kmTGpR8DVOvIiLIsFaPH4jSygCtiCasukfP9DgY7v12fZY=,iv:KSyLkBrKpJSxjGIgW3+4smAe0kteLQJAcQ8mYIVsmo8=,tag:VuA4l9MujsD919HAodAcrw==,type:str]
    version: 3.13.3
