apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:P2jXL4FdHN2MftCGFhmQ3PzpqPbw5gjRmkxO0Lynqi2W+B6YaYVXsofHlhiRUZw9aPpJIrPL3qsmUOAT9k3EMLpFCkbjJYQEERCdv8wrLjCWUmNBBahthv76ToJoh8fQbqpVBee+dsR6QkgBOg3q4wV5PZTCZ2jeaaTjPn9w9oi3p04DLSN1bo5SJwirSx7Z5Vxk+zJ/4MSz1C/kJxFtNWyEssV2zziXLC9r772R563UZVV+TfKN8qBj6eAAYmUtqZ52FLBeIEzLsGUYiuuYWn5vIPQPqzbeNTcY6TMIB9KA/6WAtJVsjsbeMGI=,iv:88aLPTxIr1RIVSKdJA2I+eJSFRSXHCfCig5OtEw2xSA=,tag:+ciUqPY4KQb65cPSXSPUiA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWURRZTdIQi9YektCZW9I
            T2haNW1JeHNlYWt2bytkKzhQQjNZWm8rN1JzCmtRNXp1NnBWVy9uS2o5b1N4MnFE
            OWFEamJGb0ZSZEhaTUpLWGZSZlF3dmsKLS0tIDg5eVBHcndPbG5zSXF4OUFYalJ3
            K1FOdk5sRXkzSSt6MWhoYmx3SDM4cEUKrtS5Mc0a0yPvkc3amnarSD4YiMjb3KRb
            C/cprzPYNQHrYazybwtiaaE8zBffw/fY2wb0NFxLUtcmi9gPOho+Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qq4xj5dntn0y3v4nue8mq0k2qzhj6utjc5rspazjrstp50xqs4msdlxg68
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T19:23:43Z"
    mac: ENC[AES256_GCM,data:ZKJYjqxGhCFSr0+oAvk8HZYusc+nXZ5wYlHzYHR3y+nnU/CPZ1LdyJ896dB6mjnPjF/KQ3AtiQxyLHw/ioBP3Gu8hQP00V0kScTIv0fcZmmYrxxyGebIwAe3yNl8ZRr298sxpt4Cegi8xY8fo20LVszJucOOcO+r8/tvsxUF8OQ=,iv:4EBXFbGF4nt+vuvaTtxdSkFTm7mRecT//wxA4BDvzik=,tag:wGcLmb/TOBRhyQdqQR+4HQ==,type:str]
    version: 3.13.3
