apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.9.1"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    env:
      REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
      DB_HOSTNAME: '{{ printf "%s-postgresql" .Release.Name }}' # Updated to reference deployed PostgreSQL
      DB_USERNAME: "postgres"
      DB_DATABASE_NAME: "immich"
      DB_PASSWORD: password
      IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
    
    image:
      tag: v1.119.0

    immich:
      metrics:
        enabled: false
      persistence:
        library:
          existingClaim: immich-pvc
          accessMode: ReadWriteMany
      configuration: {}

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false

    postgresql:
      enabled: true
      auth:
        username: postgres
        password: password
        database: immich
      primary:
        persistence:
          enabled: true
          storageClass: nfs-csi
          size: 10Gi
          accessMode: ReadWriteMany

    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent

    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        pullPolicy: IfNotPresent
      env:
        TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          size: 5Gi
          type: emptyDir
          accessMode: ReadWriteMany