apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.9.1" # version from chart.yaml
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    env:
      REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
      DB_HOSTNAME: "immich-postgres-postgresql.immich.svc.cluster.local" # Update DB_HOSTNAME
      DB_USERNAME: "postgres" # Update DB_USERNAME
      DB_DATABASE_NAME: "postgres" # Update DB_DATABASE_NAME
      DB_PASSWORD: password # Update DB_PASSWORD
      IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
    
    image:
      tag: v1.119.0

    immich:
      metrics:
        enabled: false
      persistence:
        library:
          existingClaim: immich-pvc # Remove existingClaim since we will use storageClass
          # storageClass: nfs-csi # Specify the storage class
          accessMode: ReadWriteMany # Specify Access Mode
          # size: 20Gi # Specify the size of the volume
      configuration: {}

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false

    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent

    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        pullPolicy: IfNotPresent
      env:
        TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          size: 5Gi
          type: emptyDir
          accessMode: ReadWriteMany
